// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rnovcrcvhaeuudqkymiw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJub3ZjcmN2aGFldXVkcWt5bWl3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDY5OTQsImV4cCI6MjA2NTU4Mjk5NH0.He7UXOBmk7Vx5CW49Li7Im1pgFKEoIB7WedXyhzcxdI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);